export const employees = [
    { photo: `https://www.pngmart.com/files/21/Female-Doctor-PNG-Transparent.png`,
      telephone: 483920293,
      name: "Elisa Peeters",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Radioloog",

    },
    { photo: `https://pngimg.com/uploads/doctor/small/doctor_PNG16035.png`,
      telephone: 483920293,
      name: "Pim Heike",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Anesthesioloog",

    },

    { photo: `https://nurseed101.s3.amazonaws.com/2021/08/lady_new.png`,
      telephone: 483920293,
      name: "Cor Juul",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Chirurg",

    },
    { photo: `https://www.pngpix.com/wp-content/uploads/2016/03/Doctor-PNG-Image.png`,
      telephone: 483283937,
      name: "Gilbert Ruben",
      email: "gilbert_ruben@test.be",
      city: "Brugge",
      specialization: "Cardioloog",

    },
    { photo: `https://www.amnhealthcare.com/siteassets/staffing/nursing/travel-nurse/testimonial-card-manager.png`,
      telephone: 483920293,
      name: "Reinout Klazina",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Microbioloog",

    },
    { photo: `https://www.biomarkdiagnostics.com/wp-content/uploads/2021/04/biomark-diagnostics-home-page-main-image-doctor-cancer-research.png`,
      telephone: 483920293,
      name: "Senn Carla",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Neuroloog",

    },
    { photo: `https://freepngimg.com/thumb/nurse/6-2-nurse-png-clipart-thumb.png`,
      telephone: 483920293,
      name: "Koert Marianne",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Oogarts",

    },
    { photo: `https://freepngimg.com/thumb/nurse/7-2-nurse-picture-thumb.png`,
      telephone: 483920293,
      name: "Eva Albert",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Pulmonologie",

    },
    { photo: `https://freepngimg.com/save/15002-nurse-free-png-image/867x999`,
      telephone: 483920293,
      name: "Natasja Ward",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Oncoloog",

    },
    { photo: `https://pngimg.com/uploads/doctor/doctor_PNG15980.png`,
      telephone: 483920293,
      name: "Tycho Maaike",
      email: "elisa_12@test.be",
      city: "Brugge",
      specialization: "Cardioloog",

    },
    { photo: `https://www.pngall.com/wp-content/uploads/2018/05/Doctor-PNG-Clipart.png`,
      telephone: 489372845,
      name: "Mike Maes",
      email: "mike_maes@test.be",
      city: "Antwerpen",
      specialization: "Dermatoloog",
    },
    { photo: `https://www.pngall.com/wp-content/uploads/2018/05/Doctor-PNG-Images.png`,
      telephone: 497272174,
      name: "Maria Van Horen",
      email: "maria_horen@test.be",
      city: "Sint-Josef",
      specialization: "Endocrinoloog",
    },
    { photo: `https://cdn.shopify.com/s/files/1/0012/8440/7394/files/Nurse.png?v=1625600171`,
      telephone: 472839322,
      name: "Dorine Maart",
      email: "george_janssens@test.be",
      city: "Mechelen",
      specialization: "Gynaecoloog",
    },
    { photo: `https://assets.webiconspng.com/uploads/2017/09/Doctors-And-Nurses-PNG-Image-24345.png`,
      telephone: 472839322,
      name: "Alexander Cook",
      email: "george_janssens@test.be",
      city: "Mechelen",
      specialization: "Radioloog",
    },
    { photo: `https://pngimg.com/uploads/doctor/small/doctor_PNG16017.png`,
      telephone: 472839322,
      name: "Kevin Maes",
      email: "george_janssens@test.be",
      city: "Mechelen",
      specialization: "Tandarts",
    },
    { photo: `https://www.freepnglogos.com/uploads/doctor-png/basic-ideas-for-logical-programs-for-doctor-home-loan-6.png`,
      telephone: 472839322,
      name: "George Janssens",
      email: "george_janssens@test.be",
      city: "Mechelen",
      specialization: "Uroloog",
    },
  ];

